name: Rust
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  compile:
    name: Compile wat to wasm
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: kirillt/wabt
          options: -v ${{ github.workspace }}:/src -w /src
          run: |
            ./build.sh CI
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Wasm File
          path: wasm
  build:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - uses: actions/download-artifact@v2
        with:
          name: Wasm File
          path: wasm
      - name: Run tests
        run: ls -la wasm && ls -la && cargo test --verbose