name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    name: Compile site assets
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: kirillt/wabt
          options: -v ${{ github.workspace }}:/src -w /src
          run: |
            wat2wasm wat/add.wat -o wasm/add.wasm
            wat2wasm wat/simple-import.wat -o wasm/simple-import.wasm
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Wasm File
          path: wasm

  build:
    needs: compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Wasm File
      - uses: actions/checkout@v3
      - name: Build
        run: ls -la wasm && cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
